# Generated by Django 4.1.3 on 2022-12-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='grado_praentesco',
            new_name='grado_parentesco',
        ),
    ]
