# Generated by Django 4.1.3 on 2022-12-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_rename_grado_praentesco_familiares_grado_parentesco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='fecha_nacimimento',
            new_name='fecha_nacimiento',
        ),
    ]
